### ISSUE TITLE
About running error

### ISSUE THREAD

**Issue by decade2204** [Demon0312/FER#1]
Hello! This is really a great work! But now I have a running error which during the tsp problem training:
<img width="605" alt="0098901b4d68d95d52cb6cae4264b15" src="https://github.com/Demon0312/Feature-Embedding-Refiner/assets/45782809/a253d46c-ac52-4525-b786-9d74e0c324f8">
Traceback (most recent call last):
  File "C:\Users\Administrator\Desktop\Feature-Embedding-Refiner-master\FER-AM\run.py", line 10, in <module>
    from problems.tsp.problem_tsp import TSP
  File "C:\Users\Administrator\Desktop\Feature-Embedding-Refiner-master\FER-AM\problems\tsp\problem_tsp.py", line 8, in <module>
    from problems.tsp.state_tsp import StateTSP
  File "C:\Users\Administrator\Desktop\Feature-Embedding-Refiner-master\FER-AM\problems\tsp\state_tsp.py", line 6, in <module>
    class StateTSP(NamedTuple):
RuntimeError: __class__ not set defining 'StateTSP' as <class 'problems.tsp.state_tsp.StateTSP'>. Was __classcell__ propagated to type.__new__?

**Comment by majixin-li** [comment]
I had the same problem. How did you solve it?
